# Generated by Django 5.0 on 2024-01-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_passwd',
            new_name='user_password',
        ),
    ]
